services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_trt_remote_db
    restart: always
    environment:
      MARIADB_USER: LOCAL_ADMIN
      MARIADB_PASSWORD: "abc123."
      MARIADB_DATABASE: establishment
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "9000:3306"
    networks:
      - trt-net
  
  camelot-server:
    image: ubuntu:latest
    container_name: camelot_server
    restart: always
    volumes:
      - ./trt-camelot/target/x86_64-unknown-linux-gnu/release/camelot:/usr/local/bin/camelot
    command:
      - "/usr/local/bin/camelot"
    networks:
      - trt-net
    
networks:
  trt-net:
    driver: bridge
