#yaml-language-server: $schema=https://lebastudios.org/schemas/trt-help-entry-metadata.yaml
fileFormatVersion: 1
helpEntryType: MD
name: Users
defaultLocale: en
keywords:
  - accounts
  - users
  - admin
controllers:
  - org.lebastudios.theroundtable.config.AccountConfigPaneController