#yaml-language-server: $schema=https://lebastudios.org/schemas/trt-help-entry-metadata.yaml
fileFormatVersion: 1
helpEntryType: DIR
name: Config
defaultLocale: en
controllers:
  - org.lebastudios.theroundtable.config.ConfigStageController